/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Curtiss_T18.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Curtiss_T18.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Vertical_Stabilzer000" position={[0.007, 0.112, -0.396]} rotation={[0, 0.119, 0]} scale={[0.004, 0.049, 0.049]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Glass Shield']} position={[0, 0.07, -0.042]} scale={[0.05, 0.05, 0.115]} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Glass Shield.001']} position={[0, 0.07, 0.126]} rotation={[0.121, 0, 0]} scale={[0.04, 0.055, 0.105]} />
        <mesh name="Horizantal_Stabilizer_Left" geometry={nodes.Horizantal_Stabilizer_Left.geometry} material={materials.Body} position={[0.052, 0.045, -0.941]} scale={[-0.044, 0.029, 0.029]} />
        <mesh name="Elevator_Left" geometry={nodes.Elevator_Left.geometry} material={materials.Body} position={[0.052, 0.045, -0.941]} scale={[-0.044, 0.029, 0.029]} />
        <mesh name="Elevator_Right" geometry={nodes.Elevator_Right.geometry} material={materials.Body} position={[-0.053, 0.045, -0.941]} scale={[0.044, 0.029, 0.029]} />
        <mesh name="Horizantal_Stabilizer_Right" geometry={nodes.Horizantal_Stabilizer_Right.geometry} material={materials.Body} position={[-0.053, 0.045, -0.941]} scale={[0.044, 0.029, 0.029]} />
        <mesh name="wheels002" geometry={nodes.wheels002.geometry} material={materials.Tires} position={[0.101, -0.161, 0.18]} rotation={[0, 0, -Math.PI / 2]} scale={[0.123, 0.16, 0.123]} />
        <mesh name="Back_Seat_Frame" geometry={nodes.Back_Seat_Frame.geometry} material={materials.Wood} position={[0, 0.002, -0.087]} scale={[0.142, 0.13, 0.122]} />
        <group name="Front_Seat_Frame" position={[0, 0.002, -0.087]} scale={[0.142, 0.13, 0.122]}>
          <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.Wood} />
          <mesh name="Plane011_1" geometry={nodes.Plane011_1.geometry} material={materials.Body} />
        </group>
        <mesh name="wheels001" geometry={nodes.wheels001.geometry} material={materials.Tires} position={[0.101, -0.161, 0.18]} rotation={[0, 0, -Math.PI / 2]} scale={[0.123, 0.16, 0.123]} />
        <mesh name="Cords001" geometry={nodes.Cords001.geometry} material={materials.Wood} position={[-0.687, 0.005, 0.079]} rotation={[0, 0, 0.667]} scale={[0.004, -0.097, 0.001]} />
        <group name="Rudder" position={[0, 0.112, -0.396]} rotation={[0, 0.003, 0]} scale={[0.004, 0.049, 0.049]}>
          <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.Red} />
          <mesh name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={materials.White} />
          <mesh name="Cube013_2" geometry={nodes.Cube013_2.geometry} material={materials.Blue} />
        </group>
        <mesh name="SC40054" geometry={nodes.SC40054.geometry} material={materials.Tires} position={[-0.003, 0.186, -0.545]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.018} />
        <mesh name="Exhust" geometry={nodes.Exhust.geometry} material={materials['Minor Cords']} position={[-0.055, 0.022, 0.198]} scale={[0.003, 0.043, 0.003]} />
        <mesh name="Rotors" geometry={nodes.Rotors.geometry} material={materials.Wood} position={[0, 0, -0.064]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Rotor_Base" geometry={nodes.Rotor_Base.geometry} material={materials['Minor Cords']} position={[-0.086, 0.009, 0.376]} rotation={[1.571, -1.562, 0]} scale={-0.013} />
        <mesh name="wheels" geometry={nodes.wheels.geometry} material={materials['Minor Cords']} position={[0.101, -0.161, 0.18]} rotation={[0, 0, -Math.PI / 2]} scale={[0.123, 0.16, 0.123]} />
        <mesh name="Cords" geometry={nodes.Cords.geometry} material={materials['Minor Cords']} position={[-0.687, 0.005, 0.079]} rotation={[0, 0, 0.667]} scale={[0.004, -0.097, 0.001]} />
        <mesh name="Wing" geometry={nodes.Wing.geometry} material={materials.Body} position={[0.498, 0.188, 0.092]} rotation={[0, 0.061, 0]} scale={[0.07, 0.005, 0.07]} />
        <mesh name="Vertical_Stabilzer001" geometry={nodes.Vertical_Stabilzer001.geometry} material={materials.Body} position={[0.007, 0.112, -0.396]} rotation={[0, 0.119, 0]} scale={[0.004, 0.049, 0.049]} />
        <mesh name="Body" geometry={nodes.Body.geometry} material={materials.Body} position={[0, 0.002, -0.087]} scale={[0.142, 0.13, 0.122]} />
        <mesh name="USNAVY_3" geometry={nodes.USNAVY_3.geometry} material={materials.Tires} position={[-0.159, 0.009, -0.345]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.055, 0.055, 0.088]} />
        <mesh name="Right_Side_View" geometry={nodes.Right_Side_View.geometry} material={nodes.Right_Side_View.material} position={[-0.024, 0.042, 0.007]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Front_View" geometry={nodes.Front_View.geometry} material={nodes.Front_View.material} position={[0.049, 0.047, -0.535]} rotation={[1.508, -0.344, -0.185]} scale={[0.86, 0.955, 0.955]} />
        <mesh name="Top_View" geometry={nodes.Top_View.geometry} material={nodes.Top_View.material} position={[0.003, -0.196, 0.014]} rotation={[0, 1.571, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Curtiss_T18.glb')
